# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a576c8d9271ff4157decc44c6dfa9741"
name = "haider-price-app-newest"
handle = "haider-price-app-newest"
application_url = "https://sword-those-detect-colleges.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://sword-those-detect-colleges.trycloudflare.com/auth/callback",
  "https://sword-those-detect-colleges.trycloudflare.com/auth/shopify/callback",
  "https://sword-those-detect-colleges.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
